// Mock order and wishlist data for testing
import type {
  OrderDetail,
  WishlistItem,
  PagedResult,
} from "@/types/orderTypes";

export const MOCK_ORDERS: OrderDetail[] = [
  {
    id: "ORD-2025-001",
    date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Delivered",
    items: 3,
    total: 249.99,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: "TRK123456789",
    estimatedDelivery: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "1",
        name: "Premium Wireless Headphones",
        image: "/placeholder.png",
        quantity: 1,
        price: 149.99,
        variant: "Black",
      },
      {
        productId: "item-2",
        name: "USB-C Cable (2m)",
        image: "/placeholder.png",
        quantity: 2,
        price: 50.0,
        variant: "White",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Your order has been received",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 4 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order is being prepared",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package is on the way",
      },
      {
        status: "Delivered",
        date: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package delivered successfully",
      },
    ],
  },
  {
    id: "ORD-2025-002",
    date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Shipped",
    items: 2,
    total: 89.99,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: "TRK987654321",
    estimatedDelivery: new Date(Date.now() + 1 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-3",
        name: "Smartphone Case",
        image: "/placeholder.png",
        quantity: 1,
        price: 29.99,
        variant: "Clear",
      },
      {
        productId: "item-4",
        name: "Screen Protector",
        image: "/placeholder.png",
        quantity: 1,
        price: 60.0,
        variant: "Tempered Glass",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Your order has been received",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order is being prepared",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package is on the way",
      },
      {
        status: "Out for Delivery",
        date: new Date().toISOString(),
        completed: false,
        description: "Package will be delivered today",
      },
    ],
  },
  {
    id: "ORD-2025-003",
    date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Processing",
    items: 1,
    total: 599.99,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: null,
    estimatedDelivery: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-5",
        name: "Ergonomic Laptop Stand",
        image: "/placeholder.png",
        quantity: 1,
        price: 599.99,
        variant: "Aluminum - Silver",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Your order has been received",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order is being prepared",
      },
    ],
  },
  {
    id: "ORD-2024-004",
    date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Delivered",
    items: 5,
    total: 1249.95,
    currency: "GEL",
    shippingAddress: "456 Tech Plaza, Office 12, Tbilisi, 0186",
    trackingNumber: "TRK555777999",
    estimatedDelivery: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-6",
        name: "4K Ultra HD Webcam",
        image: "/placeholder.png",
        quantity: 1,
        price: 299.99,
        variant: "Pro Edition",
      },
      {
        productId: "item-7",
        name: "RGB Desk Mat",
        image: "/placeholder.png",
        quantity: 1,
        price: 49.99,
        variant: "XXL - Black",
      },
      {
        productId: "item-8",
        name: "Wireless Charging Pad",
        image: "/placeholder.png",
        quantity: 2,
        price: 39.99,
        variant: "15W Fast Charge",
      },
      {
        productId: "item-9",
        name: "Blue Light Glasses",
        image: "/placeholder.png",
        quantity: 1,
        price: 79.99,
        variant: "Classic Frame",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Your order has been received",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 44 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Payment confirmed",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 42 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package shipped via Express Delivery",
      },
      {
        status: "Delivered",
        date: new Date(Date.now() - 40 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Successfully delivered to reception",
      },
    ],
  },
  {
    id: "ORD-2024-005",
    date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Delivered",
    items: 2,
    total: 1899.98,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: "TRK111222333",
    estimatedDelivery: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-10",
        name: '27" 4K Monitor',
        image: "/placeholder.png",
        quantity: 1,
        price: 1399.99,
        variant: "IPS - USB-C Hub",
      },
      {
        productId: "item-11",
        name: "Monitor Calibrator",
        image: "/placeholder.png",
        quantity: 1,
        price: 499.99,
        variant: "Professional",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order confirmed",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 59 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Quality check completed",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 57 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package in transit",
      },
      {
        status: "Delivered",
        date: new Date(Date.now() - 55 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Delivered and signed for",
      },
    ],
  },
  {
    id: "ORD-2024-006",
    date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Delivered",
    items: 4,
    total: 379.96,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: "TRK444666888",
    estimatedDelivery: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-12",
        name: "Noise Cancelling Earbuds",
        image: "/placeholder.png",
        quantity: 1,
        price: 199.99,
        variant: "White",
      },
      {
        productId: "item-13",
        name: "Portable SSD 1TB",
        image: "/placeholder.png",
        quantity: 1,
        price: 119.99,
        variant: "Thunderbolt 3",
      },
      {
        productId: "item-14",
        name: "Cable Management Kit",
        image: "/placeholder.png",
        quantity: 1,
        price: 29.99,
        variant: "Premium Bundle",
      },
      {
        productId: "item-15",
        name: "Desk Lamp LED",
        image: "/placeholder.png",
        quantity: 1,
        price: 29.99,
        variant: "Warm White",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 90 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order received",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 89 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Items picked from warehouse",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 87 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "In transit to your location",
      },
      {
        status: "Delivered",
        date: new Date(Date.now() - 85 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Package delivered successfully",
      },
    ],
  },
  {
    id: "ORD-2024-007",
    date: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
    status: "Delivered",
    items: 3,
    total: 699.97,
    currency: "GEL",
    shippingAddress: "123 Main St, Apt 4B, Tbilisi, 0160",
    trackingNumber: "TRK222444666",
    estimatedDelivery: new Date(Date.now() - 115 * 24 * 60 * 60 * 1000).toLocaleDateString(),
    orderItems: [
      {
        productId: "item-16",
        name: "Smart Watch Pro",
        image: "/placeholder.png",
        quantity: 1,
        price: 449.99,
        variant: "Black - 45mm",
      },
      {
        productId: "item-17",
        name: "Watch Band Leather",
        image: "/placeholder.png",
        quantity: 1,
        price: 89.99,
        variant: "Brown",
      },
      {
        productId: "item-18",
        name: "Wireless Power Bank",
        image: "/placeholder.png",
        quantity: 1,
        price: 159.99,
        variant: "20000mAh",
      },
    ],
    trackingSteps: [
      {
        status: "Order Placed",
        date: new Date(Date.now() - 120 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Order confirmed",
      },
      {
        status: "Processing",
        date: new Date(Date.now() - 119 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Payment processed",
      },
      {
        status: "Shipped",
        date: new Date(Date.now() - 117 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Shipped via standard delivery",
      },
      {
        status: "Delivered",
        date: new Date(Date.now() - 115 * 24 * 60 * 60 * 1000).toISOString(),
        completed: true,
        description: "Delivered successfully",
      },
    ],
  },
];

export const MOCK_WISHLIST: WishlistItem[] = [
  {
    id: "wish-1",
    name: "Mechanical Keyboard RGB",
    image: "/placeholder.png",
    price: 189.99,
    currency: "GEL",
  },
  {
    id: "wish-2",
    name: "Gaming Mouse Pro",
    image: "/placeholder.png",
    price: 129.99,
    currency: "GEL",
  },
  {
    id: "wish-3",
    name: "Adjustable Monitor Arm Dual",
    image: "/placeholder.png",
    price: 149.99,
    currency: "GEL",
  },
  {
    id: "wish-4",
    name: "Standing Desk Electric",
    image: "/placeholder.png",
    price: 799.99,
    currency: "GEL",
  },
  {
    id: "wish-5",
    name: "Ergonomic Office Chair",
    image: "/placeholder.png",
    price: 599.99,
    currency: "GEL",
  },
  {
    id: "wish-6",
    name: "Wireless Earbuds Pro Max",
    image: "/placeholder.png",
    price: 249.99,
    currency: "GEL",
  },
  {
    id: "wish-7",
    name: '34" Ultrawide Curved Monitor',
    image: "/placeholder.png",
    price: 1299.99,
    currency: "GEL",
  },
  {
    id: "wish-8",
    name: "Studio Microphone USB",
    image: "/placeholder.png",
    price: 179.99,
    currency: "GEL",
  },
  {
    id: "wish-9",
    name: 'Tablet 12.9" 256GB',
    image: "/placeholder.png",
    price: 1099.99,
    currency: "GEL",
  },
  {
    id: "wish-10",
    name: "Smart Home Hub",
    image: "/placeholder.png",
    price: 89.99,
    currency: "GEL",
  },
  {
    id: "wish-11",
    name: "Noise Cancelling Headphones Premium",
    image: "/placeholder.png",
    price: 399.99,
    currency: "GEL",
  },
  {
    id: "wish-12",
    name: "Graphics Tablet Pro",
    image: "/placeholder.png",
    price: 649.99,
    currency: "GEL",
  },
];

export function getMockOrders(page: number = 1, pageSize: number = 10): PagedResult<OrderDetail> {
  const start = (page - 1) * pageSize;
  const end = start + pageSize;

  return {
    page,
    pageSize,
    total: MOCK_ORDERS.length,
    data: MOCK_ORDERS.slice(start, end),
  };
}

export function getMockOrderById(id: string): OrderDetail | null {
  return MOCK_ORDERS.find((order) => order.id === id) || null;
}

export function getMockWishlist(): WishlistItem[] {
  return MOCK_WISHLIST;
}
